apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: ip-bumgu-gw
  namespace: personal-api
spec:
  gatewayClassName: traefik
  listeners:
    - name: web
      protocol: HTTP
      port: 80
      allowedRoutes:
        namespaces:
          from: Same
    - name: web-secure
      protocol: HTTPS
      port: 443
      tls:
        mode: Terminate
        certificateRefs:
          - name: k8s-bumgu-com-tls
      allowedRoutes:
        namespaces:
          from: Same
