apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: ip-bumgu-web-route
  namespace: personal-api
spec:
  parentRefs:
    - name: ip-bumgu-gw
  hostnames:
    - ip.k8s.bumgu.com
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: ip-bumgu-com-svc
          port: 8080
