apiVersion: apps/v1
kind: Deployment
metadata:
  name: phonelink-backend-deployment
  namespace: phonelink
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ph-backend
  template:
    metadata:
      labels:
        app: ph-backend
    spec:
      containers:
        - name: ph-backend
          image: ghcr.io/phone-link-org/phone-link/backend
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: "/app/uploads"
              name: uploads-volume
          envFrom:
            - secretRef:
                name: phonelink-backend-secrets
      volumes:
        - name: uploads-volume
          persistentVolumeClaim:
            claimName: ph-backend-pvc
      imagePullSecrets:
        - name: phonelink-packages
