apiVersion: apps/v1
kind: Deployment
metadata:
  name: phonelink-backend-deployment
  namespace: phonelink
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ph-backend
  template:
    metadata:
      labels:
        app: ph-backend
    spec:
      containers:
        - name: ph-backend
          image: ghcr.io/phone-link-org/phone-link/backend
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: "/app/uploads"
              name: uploads-volume
      volumes:
        - name: uploads-volume
          persistentVolumeClaim:
            claimName: ph-backend-pvc
          env:
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: phonelink-backend-secrets
                  key: PORT
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: phonelink-backend-secrets
                  key: DATABASE_HOST
            - name: DATABASE_PORT
              valueFrom:
                secretKeyRef:
                  name: phonelink-backend-secrets
                  key: DATABASE_PORT
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: phonelink-backend-secrets
                  key: DATABASE_USER
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: phonelink-backend-secrets
                  key: DATABASE_PASSWORD
            - name: DATABASE_NAME
              valueFrom:
                secretKeyRef:
                  name: phonelink-backend-secrets
                  key: DATABASE_NAME
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: phonelink-backend-secrets
                  key: JWT_SECRET
            - name: JWT_SIGNUP_SECRET
              valueFrom:
                secretKeyRef:
                  name: phonelink-backend-secrets
                  key: JWT_SIGNUP_SECRET
            - name: PHONE_LINK_CLIENT_URL
              valueFrom:
                secretKeyRef:
                  name: phonelink-backend-secrets
                  key: PHONE_LINK_CLIENT_URL
            - name: NAVER_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: phonelink-backend-secrets
                  key: NAVER_CLIENT_ID
            - name: NAVER_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: phonelink-backend-secrets
                  key: NAVER_CLIENT_SECRET
            - name: KAKAO_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: phonelink-backend-secrets
                  key: KAKAO_CLIENT_ID
            - name: KAKAO_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: phonelink-backend-secrets
                  key: KAKAO_CLIENT_SECRET
            - name: KAKAO_ADMIN_KEY
              valueFrom:
                secretKeyRef:
                  name: phonelink-backend-secrets
                  key: KAKAO_ADMIN_KEY
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: phonelink-backend-secrets
                  key: SECRET_KEY
            - name: ENVIRONMENT
              valueFrom:
                secretKeyRef:
                  name: phonelink-backend-secrets
                  key: ENVIRONMENT
      imagePullSecrets:
        - name: phonelink-packages
