apiVersion: apps/v1
kind: Deployment
metadata:
  name: grammair-web-deployment
  namespace: grammair
spec:
  selector:
    matchLabels:
      app: grammair-web
  template:
    metadata:
      labels:
        app: grammair-web
    spec:
      containers:
        - name: grammair-web
          image: ghcr.io/bonzonkim/grammair-web/grammair-web
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: grammair-web-cm
            - secretRef:
                name: grammair-web-secret
      imagePullSecrets:
        - name: grammair-packages
